config/routes.rb
Rails.application.routes.draw do
  get 'dragon_trainings/new'
  get 'trainings/index'
  get 'food_times/new'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'dragon/new'
  get 'resource/new'
  get 'dragon_types/index'
  get 'dragons_teams/index'
  get 'resources/index'
  get 'expeditions/index'
  get 'food_times/new'
  get 'trainings/index'
  get 'dragon_trainings/index'
  get 'dragon_tombstones/index'
  root 'dragon_types#index'

  resources :dragons_teams
  resources :dragon_types
  resources :resources
  resources :resource_types
  resources :food_times
  resources :trainings
  resources :dragon_trainings
  resources :dragon_tombstones

  resources :expeditions
  resources :expedition_types
  resources :expedition_prizes

  namespace :user do
    root to: 'profile#index'
  end

  namespace :api do
    get 'users/email_exists', to: 'users#email_exists'

    resources :dragons_teams, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/resource_types_controller.rb
class ResourceTypesController < ApplicationController
  def index
    @resource_type = ResourceType.all
  end

  def show
    @resource_type = ResourceType.find(params[:id])
  end

  private

  def resource_type_params
    params.require(:resource_types).permit(:name, :description)
  end
end

app/views/resource_types/index.html.slim
h1 Listing all resource types

table.table
  - @resource_type.each do |resource|
    tr
      td= image_tag resource.thumbnail.variant(resize: "50x50")
      td
        = "#{resource.name}"
      td
        = "#{resource.description}"
      td= link_to 'Show', resource_type_path(resource)

app/views/resource_types/show.html.slim
p
  = image_tag @resource_type.thumbnail.variant(resize: "150x150")
p
  strong Name:
  = @resource_type.name
p
  strong Description:
  = @resource_type.description

  br
  = link_to 'Back', resource_types_path