config/routes.rb
Rails.application.routes.draw do
  get 'dragon_trainings/new'
  get 'trainings/index'
  get 'food_times/new'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'dragon/new'
  get 'resource/new'
  get 'dragon_types/index'
  get 'dragons_teams/index'
  get 'resources/index'
  get 'expeditions/index'
  get 'food_times/new'
  get 'trainings/index'
  get 'dragon_trainings/index'
  get 'dragon_tombstones/index'
  root 'dragon_types#index'

  resources :dragons_teams
  resources :dragon_types
  resources :resources
  resources :resource_types
  resources :food_times
  resources :trainings
  resources :dragon_trainings
  resources :dragon_tombstones

  resources :expeditions
  resources :expedition_types
  resources :expedition_prizes

  namespace :user do
    root to: 'profile#index'
  end

  namespace :api do
    get 'users/email_exists', to: 'users#email_exists'

    resources :dragons_teams, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/edit.html.slim
= form_with(model: @resource, local: true) do |resrc|
  p
    = resrc.label :"What's new value?"
    br
    = resrc.number_field :quantity, min: 0
  p
    = resrc.submit
  = link_to 'Back', resource_path(@resource)

app/views/resources/index.html.slim
= link_to root_path do
  strong Back to main page

h3
  = "Resources:"
ul
  - @current_user.resources.each do |resource|
    .col-sm-6
      p
        = image_tag resource.resource_type.thumbnail.variant(resize: "150x150")
	  p
        = "#{resource.resource_type.name}: #{resource.quantity}"

app/views/resources/show.html.slim
p
  = image_tag @resource.resource_type.thumbnail.variant(resize: "150x150")
p
  strong Name:
  = @resource.resource_type.name
p
  strong Quantity:
  = @resource.quantity
p
  strong Description:
  = @resource.resource_type.description
br
  = link_to 'Edit', edit_resource_path(@resource)
  = link_to 'Back', resources_path(@resource)