config/routes.rb
Rails.application.routes.draw do
  get 'dragon_trainings/new'
  get 'trainings/index'
  get 'food_times/new'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'dragon/new'
  get 'resource/new'
  get 'dragon_types/index'
  get 'dragons_teams/index'
  get 'resources/index'
  get 'expeditions/index'
  get 'food_times/new'
  get 'trainings/index'
  get 'dragon_trainings/index'
  get 'dragon_tombstones/index'
  root 'dragon_types#index'

  resources :dragons_teams
  resources :dragon_types
  resources :resources
  resources :resource_types
  resources :food_times
  resources :trainings
  resources :dragon_trainings
  resources :dragon_tombstones

  resources :expeditions
  resources :expedition_types
  resources :expedition_prizes

  namespace :user do
    root to: 'profile#index'
  end

  namespace :api do
    get 'users/email_exists', to: 'users#email_exists'

    resources :dragons_teams, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expedition.rb
class Expedition < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :dragon, optional: true
  belongs_to :expedition_type, optional: true

  DEATH_CHANCE = 0

  def resolve_expedition
    if dragon_survive?
      alert = ClaimPrize.run!(user: user, expedition: self)
    else
      alert = "Your dragon #{dragon.name} didn't survive expedition to #{expedition_type.name}"
      kill_dragon
    end
    alert
  end

  def dragon_survive?
    strength = dragon.get_attribute_by_name('Strength')
    survive_chance = rand(0..100)
    a = survive_chance + (strength.level / 10) >= DEATH_CHANCE
    print a
    a
  end

  def kill_dragon
    dead_dragon = DragonTombstone.create(dragon.attributes)
    dead_dragon.update_attribute(:description, "Died #{Time.now} on expedition to #{expedition_type.name}")
    dragon.destroy
    destroy
  end
end

app/models/expedition_type.rb
class ExpeditionType < ApplicationRecord
  has_many :expedition_prizes
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController
  def index
    @expedition = current_user.expeditions
    @expedition_types = ExpeditionType.where(ExpeditionType.arel_table[:user_level].lteq(current_user.level))
    @expedition_blocked = ExpeditionType.where(ExpeditionType.arel_table[:user_level].gt(current_user.level))
  end

  def show
    @expedition = @current_user.expeditions.find(params[:id])
    @prize_resources = ExpeditionPrize.where(expedition_type_id: @expedition.expedition_type)
  end

  def new
    @expedition = Expedition.new
    @expedition_type = ExpeditionType.find(params[:format])
  end

  def create
    @dragon = Dragon.find(params[:expedition][:dragon_id])
    flash[:alert] = resolve_expedition
    redirect_to expeditions_index_path(current_user.id)
  end

  def destroy
    expedition = Expedition.find(params[:id])
    alert = expedition.resolve_expedition
    flash[:alert] = alert unless alert.nil?
    redirect_to expeditions_index_path(current_user.id)
  end

  private

  def resolve_expedition
    assignment = @dragon.busy?
    if assignment.empty?
      create_expedition
    else
      assignment
    end
  end

  def create_expedition
    @expedition = current_user.expeditions.build(expedition_params)
    @expedition.start_time = DateTime.now
    if @expedition.save
      'You sent Expedition!'
      # claim_worker
    else
      @expedition.errors.full_messages
    end
  end

  def claim_worker
    ExpeditionRemoveWorker.perform_at(10.seconds.from_now, @expedition.id, @expedition.expedition_type.id, current_user.id)
    flash[:notice] = 'Expedition came back!'
  end

  def expedition_params
    params.require(:expedition).permit(:dragon_id, :expedition_type_id, :start_time)
  end
end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
end

app/views/expeditions/index.html.slim
= link_to root_path do
  strong Back to main page

h3
  = "Expeditions:"
ul
  - @current_user.expeditions.each do |expd|
    .col-sm-6
      p
        a href=expedition_path(expd)
          = "\"#{expd.expedition_type.name}\" - #{expd.dragon.name} (ends at: #{expd.start_time + expd.expedition_type.longevity})"
      p
        = link_to_if expd.start_time + expd.expedition_type.longevity < DateTime.now, 'Bring back', expedition_path(expd),
                method: :delete,
                data: { confirm: 'Are you sure?' } 

h3
  = "Create new expedition"
br
  = "Available expeditions for level #{@current_user.level} "
table.table
  thead
    tr
      th Expedition
      th Description
      th Minimum dragon level
      th Create
      th
    - @expedition_types.each do |expedition|
      tr
        td= expedition.name
        td= expedition.description
        td= expedition.dragon_level
        td= link_to 'Show', expedition_type_path(expedition)
        td= link_to 'Form new expedition', new_expedition_path(expedition)

br
h3
  = "Unavailable expeditions"

table.table
  thead
    tr
      th Expedition
      th Description
      th Minimum dragon level
      th Level for unlocking
      th
    - @expedition_blocked.each do |expedition|
      tr
        td= expedition.name
        td= expedition.description
        td= expedition.dragon_level
        td= expedition.user_level

app/views/expeditions/new.html.slim
= form_with scope: :expedition, url: expeditions_path, local: true do |expedition|
  p
    = expedition.label :"Which dragon you want to send to #{@expedition_type.name}?"
    = expedition.hidden_field :expedition_type_id, value: @expedition_type.id
    br
    = expedition.select :dragon_id, collection: Dragon.where(user_id: @current_user, level: @expedition_type.dragon_level..Float::INFINITY).collect { |dragon| [dragon.name, dragon.id] }
  p
    = expedition.submit
  = link_to 'Back', expeditions_path(@expedition)

app/views/expeditions/show.html.slim
p
  strong Quest:
  = "\"#{@expedition.expedition_type.name}\""
p 
  strong Dragon:
  = @expedition.dragon.name
  
p
  strong Start Time:
  = @expedition.start_time
p
  strong End Time:
  = @expedition.start_time + @expedition.expedition_type.longevity
p
  strong Description:
  = @expedition.expedition_type.description
p
  strong Prize:
  - @prize_resources.each do |prize_resource|
    p
      = "#{prize_resource.name} | #{prize_resource.resource_type.name}: #{prize_resource.prize}"
  
br
  = link_to 'Back', expeditions_path(@expedition)