config/routes.rb
Rails.application.routes.draw do
  get 'dragon_trainings/new'
  get 'trainings/index'
  get 'food_times/new'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'dragon/new'
  get 'resource/new'
  get 'dragon_types/index'
  get 'dragons_teams/index'
  get 'resources/index'
  get 'expeditions/index'
  get 'food_times/new'
  get 'trainings/index'
  get 'dragon_trainings/index'
  get 'dragon_tombstones/index'
  root 'dragon_types#index'

  resources :dragons_teams
  resources :dragon_types
  resources :resources
  resources :resource_types
  resources :food_times
  resources :trainings
  resources :dragon_trainings
  resources :dragon_tombstones

  resources :expeditions
  resources :expedition_types
  resources :expedition_prizes

  namespace :user do
    root to: 'profile#index'
  end

  namespace :api do
    get 'users/email_exists', to: 'users#email_exists'

    resources :dragons_teams, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dragon_types_controller.rb
class DragonTypesController < ApplicationController
  def index
    @dragon_type = DragonType.all
  end

  def show
    @dragon_type = DragonType.find(params[:id])
    @resources = DragonCost.where(dragon_type: @dragon_type)
  end

  private

  def dragon_type_params
    params.require(:dragon_types).permit(:name, :description)
  end
end

app/views/dragon_types/index.html.slim
h1 Listing all dragon types

table.table
  - @dragon_type.each do |dragon|
    tr
      td= image_tag dragon.thumbnail.variant(resize: "50x50")
      td
        = "#{dragon.name}"
      td
        = link_to 'Show more', dragon_type_path(dragon)
      td
        = link_to 'Add', new_dragons_team_path(dragon)

app/views/dragon_types/show.html.slim
p
  = image_tag @dragon_type.thumbnail.variant(resize: "200x200")
p
  strong Name:
  = @dragon_type.name
p
  strong Description:
  = @dragon_type.description
p
  strong Cost:
  - @resources.each do |resource|
    p
      = resource.resource_type.name
      | :
      = resource.cost
  br
  = link_to 'Back', dragon_types_path